# Generated by Django 3.2.3 on 2021-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_id', models.BigIntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('acceptor_id', models.BigIntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('store_addr', models.CharField(blank=True, max_length=100)),
                ('delivery_addr', models.CharField(blank=True, max_length=100)),
                ('t_type', models.CharField(choices=[('PC', 'Phone Call'), ('SP', 'Supplies'), ('OT', 'others')], default='OT', max_length=2)),
            ],
        ),
    ]
