# Generated by Django 3.2.3 on 2021-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210603_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='latitude',
            new_name='d_latitude',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='longitude',
            new_name='d_longitude',
        ),
        migrations.AddField(
            model_name='task',
            name='s_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='s_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
