# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      working-directory: ./CI

    steps:
    
      - uses: actions/checkout@master

      - name: compile
        run: ./compile.sh
        working-directory: ${{env.working-directory}}
        
      - name: test
        run: ./test.sh
        working-directory: ${{env.working-directory}}
      
      - name: deploy
        if: github.ref == 'refs/head/master'
        run: ./deploy.sh
        working-directory: ${{env.working-directory}}
