# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      working-directory: ./CI

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Set up Django
        run: |
          python -m pip install --upgrade pip
          pip install Django

      - name: compile
        run: ./compile.sh
        working-directory: ${{env.working-directory}}
        
      - name: test
        run: ./test.sh
        working-directory: ${{env.working-directory}}

  deploy:
    needs: build_and_test
    if: github.ref == 'refs/head/master'

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./CI

    steps:
      - name: deploy
        run: ./deploy.sh
        working-directory: ${{env.working-directory}}
